{"name": "test_multiplication_11[3-35]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 33 == 35\n  -33\n  +35", "trace": "num = 3, output = 35\n\n    @pytest.mark.parametrize(\"num, output\",[(1,11),(2,22),(3,35),(4,44)])\n    \n    def test_multiplication_11(num, output):\n>       assert 11*num == output\nE       assert 33 == 35\nE         -33\nE         +35\n\ntest_multiplication.py:5: AssertionError"}, "parameters": [{"name": "num", "value": "3"}, {"name": "output", "value": "35"}], "start": 1573041325511, "stop": 1573041325511, "uuid": "cfa89b06-f440-4f4d-b409-dbf3226be6fb", "historyId": "7de3c40574d6072112491f672a815b3a", "testCaseId": "fbb3b3939d9b6ef572eb6dad4a8d6884", "fullName": "test_multiplication#test_multiplication_11", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "SIVA-PC"}, {"name": "thread", "value": "8312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}